"""Public file allowlist and deployment checks; no network or credentials needed."""

import json
import math
import re
from datetime import date
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

PUBLIC_FILES = (
    "index.html", "tree.html", "nearby.html", "outbreak.html",
    "recruit.html", "clubs.html", "safety.html", "badges.html", "CNAME", "favicon.svg",
    "logo.jpg", "assets/bkg.css", "docs/mockups/mobile-readability.html",
)
PHOTO_DIRS = ("images/mugshots", "images/mugshots-override")
PHOTO_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".webp"}
US_STATE_CODES = frozenset("AL AK AZ AR CA CO CT DE DC FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY".split())
ROSTER_START = "<!-- ROSTER:START - auto-generated by scripts/build-roster.py from Google Sheet -->"


def require(condition, message):
    if not condition:
        raise ValueError(message)


def block(html, start, end):
    require(html.count(start) == html.count(end) == 1, f"Missing/duplicate markers: {start}")
    before, rest = html.split(start)
    payload, after = rest.split(end)
    require(end not in before and start not in after, f"Reversed markers: {start}")
    return payload


class PageParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links = []
        self.scripts = {}
        self.script_id = None
        self.calls = []
        self.names = []
        self.capture = None

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        for attr in ("src", "href"):
            if attrs.get(attr):
                self.links.append(attrs[attr])
        if tag == "script" and attrs.get("type") == "application/json":
            self.script_id = attrs.get("id")
            require(self.script_id and self.script_id not in self.scripts, "Missing/duplicate JSON script id")
            self.scripts[self.script_id] = ""
        classes = attrs.get("class", "").split()
        if tag == "a" and "member-callsign" in classes:
            self.capture = self.calls
            self.capture.append("")
        elif tag == "div" and "member-name" in classes:
            self.capture = self.names
            self.capture.append("")

    def handle_data(self, data):
        if self.script_id:
            self.scripts[self.script_id] += data
        if self.capture is not None:
            self.capture[-1] += data

    def handle_endtag(self, tag):
        if tag == "script":
            self.script_id = None
        if tag in ("a", "div"):
            self.capture = None


def data_payload(page, script_id, marker):
    require(script_id in page.scripts, f"Missing generated data: {script_id}")
    raw = block(page.scripts[script_id], f"<!-- {marker}:START -->", f"<!-- {marker}:END -->")
    def reject_constant(value):
        raise ValueError(f"Non-finite JSON number: {value}")

    try:
        return json.loads(raw, parse_constant=reject_constant)
    except (ValueError, TypeError) as exc:
        raise ValueError(f"Invalid generated JSON: {script_id}") from exc


def identity(entry):
    require(isinstance(entry, dict), "Member data must be an object")
    call, name, number = entry.get("call"), entry.get("name"), entry.get("num")
    require(isinstance(call, str) and re.fullmatch(r"[A-Za-z0-9/]+", call), "Invalid callsign")
    require(isinstance(name, str), "Invalid member name")
    require(type(number) is int and number > 0, "Invalid member number")
    return call, name, number


def coordinates(entry):
    for key, limit in (("lat", 90), ("lon", 180)):
        value = entry.get(key)
        require(type(value) in (float, int) and math.isfinite(value) and abs(value) <= limit, f"Invalid {key}")


def validate_dist(output_dir, *, source="sheets"):
    require(source in ("sheets", "json"), "Invalid build source")
    output_dir = Path(output_dir)
    required = set(PUBLIC_FILES) | {"members.txt"}
    if source == "json":
        snapshot_versions = [version for version in ("1", "2")
                             if (output_dir / f"data/v{version}/roster.json").is_file()]
        require(len(snapshot_versions) == 1, "JSON build requires exactly one versioned roster snapshot")
        snapshot_version = snapshot_versions[0]
        required.add(f"data/v{snapshot_version}/roster.json")
    actual = set()
    for path in output_dir.rglob("*"):
        require(not path.is_symlink(), f"Symlink in public output: {path}")
        if not path.is_file():
            continue
        rel = path.relative_to(output_dir).as_posix()
        photo = path.parent.relative_to(output_dir).as_posix() in PHOTO_DIRS
        require(rel in required or (photo and path.suffix.lower() in PHOTO_EXTS and not path.name.startswith(".")), f"Unexpected public file: {rel}")
        require(path.stat().st_size > 0, f"Empty public file: {rel}")
        actual.add(rel)
    require(required <= actual, f"Missing public files: {sorted(required - actual)}")
    require((output_dir / "CNAME").read_text().strip() == "www.bkg.club", "Unexpected production CNAME")

    pages = {}
    for rel in PUBLIC_FILES:
        if not rel.endswith(".html"):
            continue
        html = (output_dir / rel).read_text()
        require("<!doctype html>" in html.lower() and "</html>" in html.lower(), f"Incomplete page: {rel}")
        page = PageParser()
        page.feed(html)
        pages[rel] = page
        for link in page.links:
            url = urlsplit(link)
            if url.scheme or url.netloc or not url.path:
                continue
            target = output_dir / unquote(url.path.lstrip("/")) if url.path.startswith("/") else output_dir / Path(rel).parent / unquote(url.path)
            if url.path.endswith("/"):
                target /= "index.html"
            require(target.resolve().is_relative_to(output_dir.resolve()) and target.is_file(), f"Missing local link in {rel}: {link}")

    downline = data_payload(pages["tree.html"], "bkg-downline-data", "DOWNLINE_DATA")
    outbreak = data_payload(pages["outbreak.html"], "bkg-outbreak-data", "OUTBREAK_DATA")
    nearby = data_payload(pages["nearby.html"], "bkg-geo-data", "GEO_DATA")
    territory = data_payload(pages["index.html"], "bkg-map-data", "MAP_DATA")
    require(isinstance(downline, list) and downline, "Empty/invalid downline roster")
    identities = [identity(entry) for entry in downline]
    calls = [item[0] for item in identities]
    numbers = [item[2] for item in identities]
    require(len(set(call.upper() for call in calls)) == len(calls), "Duplicate callsign")
    require(len(set(numbers)) == len(numbers) and numbers == sorted(numbers), "Duplicate/unsorted member number")
    require(isinstance(outbreak, list) and [identity(entry) for entry in outbreak] == identities, "Outbreak roster differs from downline")
    if source == "json":
        from roster_input import parse_roster_json

        _, reviewed = parse_roster_json(
            (output_dir / f"data/v{snapshot_version}/roster.json").read_text(encoding="utf-8"),
            expected_version=snapshot_version,
        )
        require(identities == [(m["callsign"], m["name"], m["number"]) for m in reviewed],
                "Public JSON identities differ from pages")
        sponsors = {m["number"]: m["callsign"] for m in reviewed}
        require([entry["sponsor"] for entry in downline] == [
            sponsors.get(m["sponsor_bkg_number"]) for m in reviewed
        ], "Public JSON sponsors differ from pages")
        if snapshot_version == "2":
            expected_nearby = [dict(call=m["callsign"], name=m["name"], num=m["number"],
                                    **m["map_location"])
                               for m in reviewed if m["map_location"] is not None]
            require(nearby == expected_nearby, "Nearby differs from administration map locations")
    by_call = {entry["call"]: entry for entry in downline}
    for entry, ob in zip(downline, outbreak):
        sponsor = entry.get("sponsor")
        require("sponsor" in entry and (sponsor is None or (isinstance(sponsor, str) and sponsor in by_call and sponsor != entry["call"])), "Invalid sponsor")
        require({"date", "state", "dx", "sponsor"} <= ob.keys(), "Missing outbreak fields")
        require(ob["sponsor"] == sponsor, "Outbreak sponsor differs from downline")
        state, dx = ob["state"], ob["dx"]
        require(state is None or (isinstance(state, str) and state in US_STATE_CODES), "Invalid outbreak state")
        require(dx is None or (isinstance(dx, str) and bool(dx.strip())), "Invalid outbreak country")
        require(state is None or dx is None, "Member has both state and DX territory")
        if ob.get("date") is not None:
            try:
                require(date.fromisoformat(ob["date"]).isoformat() == ob["date"], "Invalid outbreak date")
            except (ValueError, TypeError) as exc:
                raise ValueError("Invalid outbreak date") from exc
        if "lat" in ob or "lon" in ob:
            coordinates(ob)

    for call in calls:
        seen = set()
        while call is not None:
            require(call not in seen, "Sponsor cycle would hide downline members")
            seen.add(call)
            call = by_call[call]["sponsor"]

    require(isinstance(nearby, list), "Invalid nearby data")
    located = []
    for entry in nearby:
        require(identity(entry) in identities, "Nearby member differs from roster")
        coordinates(entry)
        located.append(entry["call"])
        ob = outbreak[calls.index(entry["call"])]
        require((entry["lat"], entry["lon"]) == (ob.get("lat"), ob.get("lon")), "Nearby coordinates differ from outbreak")
    require(len(set(located)) == len(located), "Duplicate nearby member")
    require(set(located) == {entry["call"] for entry in outbreak if "lat" in entry}, "Nearby members differ from outbreak")
    require(isinstance(territory, dict) and set(territory) == {"states", "dx"}, "Invalid territory data")
    mapped = []
    for kind in ("states", "dx"):
        require(isinstance(territory[kind], dict), "Invalid territory buckets")
        for key, bucket in territory[kind].items():
            require(isinstance(key, str) and key, "Invalid territory key")
            require(kind != "states" or key in US_STATE_CODES, "Invalid map state")
            if kind == "dx":
                require(isinstance(bucket, dict) and isinstance(bucket.get("flag"), str), "Invalid DX bucket")
                bucket = bucket.get("members")
            require(isinstance(bucket, list) and bucket, "Empty/invalid territory bucket")
            for entry in bucket:
                require(identity(entry) in identities, "Map member differs from roster")
                ob = outbreak[calls.index(entry["call"])]
                require(ob.get("state" if kind == "states" else "dx") == key, "Map territory differs from outbreak")
                mapped.append(entry["call"])
    require(len(set(mapped)) == len(mapped), "Duplicate map member")
    require(set(mapped) == {entry["call"] for entry in outbreak if entry.get("state") or entry.get("dx")}, "Map members differ from outbreak")

    index = (output_dir / "index.html").read_text()
    require(block(index, "<!-- MEMBER_COUNT:START -->", "<!-- MEMBER_COUNT:END -->").strip() == str(len(calls)), "Member count differs from roster")
    roster = PageParser()
    roster.feed(block(index, ROSTER_START, "<!-- ROSTER:END -->"))
    require(roster.calls == calls and roster.names[:-1] == [item[1] for item in identities], "Roster cards differ from generated data")
    if source == "json":
        photos = {relative for relative in actual if Path(relative).parent.as_posix() in PHOTO_DIRS}
        require(photos <= set(roster.links), "JSON build contains photos outside the active roster")
        if snapshot_version == "2":
            from roster_assets import verify_asset

            expected_photos = {f"images/mugshots/{m['photo']['sha256']}.webp"
                               for m in reviewed if m["photo"] is not None}
            require(photos == expected_photos, "v2 photos differ from the administration snapshot")
            for member in reviewed:
                if member["photo"] is not None:
                    photo = member["photo"]
                    verify_asset((output_dir / f"images/mugshots/{photo['sha256']}.webp").read_bytes(), photo)
    card_numbers = [int(n) for n in re.findall(r'class="member-number">BKG #(\d+)</div>', block(index, ROSTER_START, "<!-- ROSTER:END -->"))]
    require(card_numbers == numbers + [max(numbers) + 1], "Roster member numbers differ from generated data")
    notes = (output_dir / "members.txt").read_text()
    require(notes.startswith("# BKG Callsign Notes for Ham2K PoLo\n"), "Invalid members.txt header")
    entries = [line for line in notes.splitlines() if line and not line.startswith("#")]
    parsed = [re.fullmatch(r"([A-Za-z0-9/]+) 🤜 (.*?) BKG #(\d+)(?: \([^\n]*\))?", line) for line in entries]
    require(all(parsed), "Invalid members.txt entry")
    require([(match[1], int(match[3])) for match in parsed] == sorted(zip(calls, numbers)), "members.txt differs from roster")
    if source == "json":
        notes_by_call = {match[1]: match[2] for match in parsed}
        require(notes_by_call == {m["callsign"]: m["name"] for m in reviewed},
                "members.txt differs from reviewed JSON names")
